### ISSUE TITLE
Support for private repos?

### ISSUE THREAD

**Issue by mdrcode** [dylang/changelog#1]
Great project. I would love to use this for tracking private repos at our startup.

Just to confirm - currently private repos are _not_ supported? AFAICT they are not as the code seems to perform an authless, no-token fetch.

**Comment by dimitrisfasoulas** [comment]
+1

**Comment by rarkins** [comment]
Given that this original request from @mdrcode was from 2011, I'm guessing he meant private *GitHub* repos, not private npm modules. This is now supported via #24 so I am closing this issue.

@dimitrisfasoulas if your +1 was for private npm modules instead, please open a new issue with any details/suggestions you have. Thanks.
