### ISSUE TITLE
Support for Github authenticated requests

### ISSUE THREAD

**Issue by guumaster** [dylang/changelog#10]
Allow to call GitHub API as an authenticated user to avoid rate limit.

**Comment by dylang** [comment]
great idea. do you have a recommended way to do this? like where do people usually store the credentials for github?

**Comment by guumaster** [comment]
There is a module called [github-oauth-prompt](https://www.npmjs.com/package/github-oauth-prompt)  to obtain a github token in a CLI script. Maybe the resulting token can be saved in the user home directory.

I'll look into it.

**Comment by rarkins** [comment]
Implemented in #24
