### ISSUE TITLE
Changelog integration with `npm outdated` of local package.json file

### ISSUE THREAD

**Issue by MaffooBristol** [dylang/changelog#15]
At the moment I'm doing `npm outdated`, then manually checking each item with changelog, which can also be a pain because I don't know how many version steps there are between my current and the newest version of a package. So it's just randomly choosing a number to put after `changelog package-name`

I think that if you're in a directory with a `package.json` file, when you run `changelog` by itself, it should be able to tell you all the version changes for every out of date package.

I can always have a look into implementing something like this myself into a PR when I get the time, but just wondering if it's a viable idea.

Thanks!

**Comment by dylang** [comment]
Thats a great idea.I was hoping to integrate this with [npm-check](https://www.npmjs.com/package/npm-check) to merge the two steps into one.

**Comment by MaffooBristol** [comment]
Oh wow, npm-check is amazing. Hadn't seen that before. Would be nice then to have a soft dependency in npm-check for changelog then, so it can give you the details of what you're upgrading!

**Comment by rarkins** [comment]
Closing, as this would be an `npm-check` enhancement and not `changelog` itself.
