### ISSUE TITLE
Any plans to support fetching the changelog from local commits and tags?

### ISSUE THREAD

**Issue by silkentrance** [dylang/changelog#17]
I'd like to incorporate this nifty tool into my build process. However, changelog does not support generating a CHANGELOG from the local commits right before they get pushed to for example github.

Do you care for a PR for this feat?

**Comment by dylang** [comment]
That would be great!

**Comment by silkentrance** [comment]
Sorry but I found ``conventional-changelog`` which does everything I need. Closing.
