### ISSUE TITLE
support for scoped npm packages

### ISSUE THREAD

**Issue by tjaartvdwalt** [dylang/changelog#18]
Somewhat related to issue #1.

It would be awesome if this worked for scoped (private) npm packages.

Currently if I run the program using my scoped package it recognizes it as a github repository:
`changelog Unknown Github Repo: @my_username/my_package. Not Found`

**Comment by dylang** [comment]
Great idea - thanks for filing the ticket. Do you want to try to create a PR for this?

**Comment by singapore** [comment]
I have raised PR #21 for this

**Comment by rarkins** [comment]
I have raised PR #21 for this
